### ISSUE TITLE
diffeqpy.de import fails with Julia 1.11.0

### ISSUE THREAD

**Issue by mcarobene-id** [SciML/diffeqpy#144]
Thank you so much for the development of `diffeqpy`! I have just started using it but finding it super helpful.

**Describe the bug 🐞**

Julia v1.11.0 was released on 08/10/24 [(announced here)](https://discourse.julialang.org/t/julia-v1-11-0-has-been-released-and-v1-10-is-now-lts/121064)

We have a docker build which would install the most recent version of Julia, then runs in python `from diffeqpy import de` to install relevant Julia packages. This started failing since the new Julia release, but I have validated that this still works if I specifically install Julia v1.10.5

**Expected behavior**

Expect to be able to import and use `diffeqpy.de`. This is 

**Minimal Reproducible Example 👇**

Note: requires that there is no existing install of Julia on machine.

From terminal:
```
pip install diffeqpy==2.4.1
jill install "1.11.0" --confirm
python -c "from diffeqpy import de"
```

**Error & Stacktrace ⚠️**

```
#14 408.8 Traceback (most recent call last):
#14 408.8 File "/app/build/install_julia.py", line 9, in <module>
#14 408.8 from diffeqpy import de
#14 408.8 File "/app/.venv/lib/python3.10/site-packages/diffeqpy/de.py", line 5, in <module>
#14 408.8 de.jit = Main.seval("jit(x) = typeof(x).name.wrapper(ModelingToolkit.complete(ModelingToolkit.modelingtoolkitize(x)), x.u0, x.tspan, x.p)") # kinda hackey
#14 408.8 File "/home/ray/.julia/packages/PythonCall/Nr75f/src/JlWrap/any.jl", line 254, in __setattr__
#14 408.8 self._jl_callmethod($(pyjl_methodnum(pyjlany_setattr)), k, v)
#14 408.8 AttributeError: Julia: Global DifferentialEquations.jit does not exist and cannot be assigned. Declare it using `global` before attempting assignment.
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `~/.julia/environments/v1.11/Project.toml` (empty project)
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
Status `~/.julia/environments/v1.11/Manifest.toml` (empty manifest)
```

  - Output of `versioninfo()`

```julia
Julia Version 1.11.0
Commit 501a4f25c2b (2024-10-07 11:40 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M3
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m3)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
```

**Comment by ChrisRackauckas** [comment]
This seems like it's due to an issue with PyCall.jl on Julia v1.11. For now the current release will just stick to v1.10 until that gets sorted out.

**Comment by lte678** [comment]
This was fixed in 657f2f6237754f335a7f22806b3c2979e76996c6
It seems diffeqpy should work with julia 1.11 starting with version 2.5.3.
