### ISSUE TITLE
AttributeError: Julia: cannot assign variables in other modules

### ISSUE THREAD

**Issue by zhan-nine** [SciML/diffeqpy#147]
**Question❓**
  While I'm trying to use diffeqpy package, I failed. Then I build a new environment, it looks like:
```
(julia_env) pkg> st
Status `E:\py3.8env\myenv38\julia_env\Project.toml`
⌅ [0c46a032] DifferentialEquations v7.10.0
⌅ [961ee093] ModelingToolkit v8.70.0
  [6099a3de] PythonCall v0.9.23
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated`
```
and 
```
Zhang Xinpei@LAPTOP-QL215LTB MINGW64 E:/Program Files/Microsoft VS Code
$ python
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from juliacall import Main
>>> Main.seval("versioninfo()")
Julia Version 1.8.4
Commit 00177ebc4f (2022-12-23 21:32 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 20 × 12th Gen Intel(R) Core(TM) i9-12900H
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, goldmont)
  Threads: 1 on 20 virtual cores
Environment:
  JULIA_DEPOT_PATH = D:\Program Files\Julia-1.8.4\.julia
  JULIA_PYTHONCALL_EXE = E:\py3.8env\myenv38\Scripts\python.exe
```
I tried your tests and my codes, both failed like:
```
Zhang Xinpei@LAPTOP-QL215LTB MINGW64 E:/Program Files/Microsoft VS Code
$ python -u "e:\py3.8env\myenv38\Lib\site-packages\diffeqpy\tests\test_ode.py"
  Activating project at `D:\Program Files\Julia-1.8.4\.julia\environments\diffeqpy`
Traceback (most recent call last):
  File "e:\py3.8env\myenv38\Lib\site-packages\diffeqpy\tests\test_ode.py", line 1, in <module>
    from diffeqpy import de
  File "E:\py3.8env\myenv38\lib\site-packages\diffeqpy\de.py", line 5, in <module>
    de.jit = Main.seval("jit(x) = typeof(x).name.wrapper(ModelingToolkit.complete(ModelingToolkit.modelingtoolkitize(x)), x.u0, x.tspan, x.p)") # kinda hackey
  File "D:\Program Files\Julia-1.8.4\.julia\packages\PythonCall\Nr75f\src\JlWrap\any.jl", line 254, in __setattr__
    self._jl_callmethod($(pyjl_methodnum(pyjlany_setattr)), k, v)
AttributeError: Julia: cannot assign variables in other modules
(myenv38) 
```
how can I use your project correctly?

**Comment by ChrisRackauckas** [comment]
`Julia Version 1.8.4`

That's really weird. It's hardcoded to install and use a Julia v1.10 installation. Because you have a much older Julia, it cannot get the right packages. Did you override the installation with the wrong version or something?

**Comment by zhan-nine** [comment]
Okay, I installed new version v1.10.5 of Julia, and I can run tests now, thanks.
