### ISSUE TITLE
pip fails to install `v2.5.3` on Windows

### ISSUE THREAD

**Issue by PositroniumJS** [SciML/diffeqpy#154]
**Describe the bug 🐞**

pip fails to install diffeqpy `2.5.3` on Windows because it cannot read the README file. If I specify to install `2.4.2`, the installation succeeds.

**Minimal Reproducible Example 👇**

`Python 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)] on win32`

**Error & Stacktrace ⚠️**

```cmd
Collecting diffeqpy
  Using cached diffeqpy-2.5.3.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\account\AppData\Local\Temp\pip-install-bfokdqa1\diffeqpy_f8a2872bb14944809187fee1187d1403\setup.py", line 10, in <module>
          long_description=readme(),
                           ^^^^^^^^
        File "C:\Users\account\AppData\Local\Temp\pip-install-bfokdqa1\diffeqpy_f8a2872bb14944809187fee1187d1403\setup.py", line 5, in readme
          return f.read()
                 ^^^^^^^^
        File "C:\Program Files\Python312\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 21618: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Additional context**
Effectively, if I download the file `README.md` from GitHub and I try to open it, I get the same error
```python
>>> f = open("README.md")
>>> f.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 21618: character maps to <undefined>
```

However, I succeed to open it if I do: `f = open("README.md", encoding="utf8")`

**Comment by serhiy-yevtushenko** [comment]
As the release 2.5.3 is still the default on pypi, and issue persists, I think that the issue should be reopened, as real fix requires the release of the new version on pypi
