### ISSUE TITLE
libjulia.so: No such file or directory

### ISSUE THREAD

**Issue by Krytic** [SciML/diffeqpy#70]
I installed `diffeqpy` and am trying to solve a simple ODE. I am not sure if this is an error with `diffeqpy` or with `julia` so forgive me if this is in the wrong place.

I run `from diffeqpy import de` and get the following error:

<details>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sean/anaconda3/lib/python3.7/site-packages/diffeqpy/de.py", line 4, in <module>
    from julia import Main
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/sean/anaconda3/lib/python3.7/site-packages/julia/core.py", line 247, in load_module
    JuliaMainModule(self, fullname))
  File "/home/sean/anaconda3/lib/python3.7/site-packages/julia/core.py", line 149, in __init__
    self._julia = loader.julia
  File "/home/sean/anaconda3/lib/python3.7/site-packages/julia/core.py", line 239, in julia
    self.__class__.julia = julia = Julia()
  File "/home/sean/anaconda3/lib/python3.7/site-packages/julia/core.py", line 468, in __init__
    jlinfo = JuliaInfo.load(runtime)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/julia/juliainfo.py", line 88, in load
    retcode, [julia, "-e", "..."], stdout, stderr
subprocess.CalledProcessError: Command '['julia', '-e', '...']' returned non-zero exit status 1.
</details>

If I run `from julia import Main` I get the same error as far as I can tell:

<details>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/sean/anaconda3/lib/python3.7/site-packages/julia/core.py", line 247, in load_module
    JuliaMainModule(self, fullname))
  File "/home/sean/anaconda3/lib/python3.7/site-packages/julia/core.py", line 149, in __init__
    self._julia = loader.julia
  File "/home/sean/anaconda3/lib/python3.7/site-packages/julia/core.py", line 239, in julia
    self.__class__.julia = julia = Julia()
  File "/home/sean/anaconda3/lib/python3.7/site-packages/julia/core.py", line 468, in __init__
    jlinfo = JuliaInfo.load(runtime)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/julia/juliainfo.py", line 88, in load
    retcode, [julia, "-e", "..."], stdout, stderr
subprocess.CalledProcessError: Command '['julia', '-e', '...']' returned non-zero exit status 1.
</details>

Digging around in the code it seems to be caused by this command: `julia --startup-file=no /home/sean/anaconda3/lib/python3.7/site-packages/julia/juliainfo.jl` which, if I run in a normal terminal instance, fails with this output:

<details>
1.4.1
1
4
1
/usr/bin
ERROR: LoadError: could not load library "libjulia"
libjulia.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] dlopen(::String, ::UInt32; throw_error::Bool) at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Libdl/src/Libdl.jl:109
 [2] dlopen at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
 [3] dlpath(::String) at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Libdl/src/Libdl.jl:232
 [4] top-level scope at /home/sean/anaconda3/lib/python3.7/site-packages/julia/juliainfo.jl:14
 [5] include(::Module, ::String) at ./Base.jl:377
 [6] exec_options(::Base.JLOptions) at ./client.jl:288
 [7] _start() at ./client.jl:484
in expression starting at /home/sean/anaconda3/lib/python3.7/site-packages/julia/juliainfo.jl:14
</details>

Critically it seems that the cause is `libjulia.so: cannot open shared object file: No such file or directory`. I can execute julia code normally through the `julia` command (e.g. `julia MyJuliaFile.jl`), just not with the examples provided in this README.

I installed julia 1.4.1 through apt (and have checked, libjulia1 is showing as installed in apt), and diffeqpy 1.1.0 though pip.

**Comment by ChrisRackauckas** [comment]
This might be an issue with the APT version? Try using the generic binary https://julialang.org/downloads/ and see if that works.

**Comment by Krytic** [comment]
That fixes this, many thanks.

This, I suppose, is an issue in julia then - I suppose I should report this upstream to them?

**Comment by ChrisRackauckas** [comment]
I think this is an issue with the apt version of Julia, so I think it's something that has to be brought up with the maintainer of that distribution.
